### ISSUE TITLE
map zoom

### ISSUE THREAD

**Issue by Mokon** [peterolson/AOE2-Real-Map-Creator#2]
It would be very nice to be able to zoom in on a map and just produce a small portion of the world. So In my case I would like to zoom into the cape area of Massachusetts and have a real world map based on that. In the current UI I can't seem to do that.

**Comment by peterolson** [comment]
You can zoom in and out with the mouse wheel

**Comment by Mokon** [comment]
Ah didn't notice that. Thanks. I guess the resolution of the dataset isn't high enough for zooming in a lot.
